-- build.lua: bundles all src/ modules into a single dist/easyswitch.lua.
-- The output file has zero require() calls and runs on any Lua 5.1+ runtime
-- (standard Lua, LuaJIT, Luau/Roblox, FiveM) without package.path setup.
--
-- Usage: lua build.lua

local MODULES = {
    { name = "src.eventManager",      file = "src/eventManager.lua" },
    { name = "src.middlewareManager", file = "src/middlewareManager.lua" },
    { name = "src.patterns",          file = "src/patterns.lua" },
    { name = "src.actionManager",     file = "src/actionManager.lua" },
    { name = "src.cacheManager",      file = "src/cacheManager.lua" },
    { name = "src.switch",            file = "src/switch.lua" },
    { name = "src.registry",          file = "src/registry.lua" },
    { name = "src.init",              file = "src/init.lua" },
}

local HEADER = [[-- EasySwitchLua (dist) — generated by build.lua, do not edit.
-- Source: https://github.com/kamion/EasySwitchLua
-- License: MIT

local _modules = {}
local function _require(name)
    local m = _modules[name]
    if not m then error("[EasySwitch] module not found: " .. name) end
    return m
end

]]

-- ── Helpers ───────────────────────────────────────────────────────────────────

local function read_file(path)
    local f = assert(io.open(path, "r"), "Cannot open: " .. path)
    local content = f:read("*a")
    f:close()
    return content
end

local function ensure_dir(path)
    local is_windows = package.config:sub(1, 1) == "\\"
    if is_windows then
        os.execute('if not exist "' .. path .. '" mkdir "' .. path .. '"')
    else
        os.execute('mkdir -p "' .. path .. '"')
    end
end

-- Replace require("src.X") / require('src.X') with _require("src.X")
local function patch_requires(src)
    src = src:gsub('require%("(src%.[^"]+)"%)', '_require("%1")')
    src = src:gsub("require%('(src%.[^']+)'%)", "_require('%1')")
    return src
end

-- ── Build ─────────────────────────────────────────────────────────────────────

local chunks = { HEADER }

for _, mod in ipairs(MODULES) do
    local src = patch_requires(read_file(mod.file))
    chunks[#chunks + 1] = '_modules["' .. mod.name .. '"] = (function()\n'
    chunks[#chunks + 1] = src
    chunks[#chunks + 1] = '\nend)()\n\n'
end

chunks[#chunks + 1] = 'return _modules["src.init"]\n'

ensure_dir("dist")

local out = assert(io.open("dist/easyswitch.lua", "w"), "Cannot write dist/easyswitch.lua")
out:write(table.concat(chunks))
out:close()

print("[build] dist/easyswitch.lua written (" .. #table.concat(chunks) .. " bytes)")
